### ISSUE TITLE
Investigate a possible abstraction between the platform and K/V stores that could allow us to support both Elasticsearch and OpenSearch.

### ISSUE THREAD

**Issue by e0d** [openedx/wg-data#1]

**Comment by crathbun428** [comment]
Closing this as not planned since we will be pursuing this through the Meliasearch work. [Investigate a possible abstraction between the platform and K/V stores that could allow us to support both Elasticsearch and OpenSearch. · Issue #1 · openedx/wg-data](https://github.com/openedx/wg-data/issues/1)
